FROM stellar/base:latest

MAINTAINER Mat Schaffer <mat@stellar.org>

EXPOSE 39133
EXPOSE 39132

VOLUME /data
VOLUME /heka

ADD stellar-core.deb /
ADD install /
RUN /install

ADD heka /heka
ADD confd /etc/confd
ADD run /

CMD ["/run"]
