FROM stellar/base:latest

MAINTAINER Mat Schaffer <mat@stellar.org>

ENV AFL_VERSION 1.83b

ADD fuzz/install /
RUN /install

VOLUME /stellar-core

ADD utils /utils
ADD fuzz/trace /
ADD fuzz/start /

CMD ["/start"]
