#!/usr/bin/env bash

CORES=$(find /cores -maxdepth 1 -name 'stellar-core*.core')

mkdir -p /cores/traces

if [[ -z "${CORES}" ]]; then
  echo No core files found
  exit 0
fi

wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -
add-apt-repository "deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main"
apt-get update -qq
apt-get install -qq libstdc++6 libpq5 lldb-3.6

cat > /etc/core_file_processor.ini <<INI
[Config]
bin=/stellar-core/bin/stellar-core
mode=local
INI

for CORE in /cores/stellar-core*.core; do
    /utils/core_file_processor.py $CORE > /cores/traces/$(basename $CORE).trace
done
