#!/usr/bin/env bash

CORES=$(find /cores -maxdepth 1 -name 'stellar-core*.core')

mkdir -p /cores/traces

if [[ -z "${CORES}" ]]; then
  echo No core files found
  exit 0
fi

wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

add-apt-repository "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main"
add-apt-repository "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main"
apt-get update -qq
apt-get install -qq libstdc++6 libpq5 lldb-5.0

cat > /etc/core_file_processor.ini <<INI
[Config]
bin=/stellar-core/src/stellar-core
mode=local
INI

for CORE in /cores/stellar-core*.core; do
    /utils/core_file_processor.py $CORE > /cores/traces/$(basename $CORE).trace
done
